### ISSUE TITLE
.NET 6.0 Compatibility?

### ISSUE THREAD

**Issue by moehoward** [VahidN/DNTCaptcha.Blazor#1]
Any desires of moving this to .NET 6.0 in the near future?

**Comment by VahidN** [comment]
Have you tested it? It should work.

**Comment by moehoward** [comment]
Error
C:\Program Files\dotnet\sdk\
6.0.100-rc.1.21463.6\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets	410

**Comment by VahidN** [comment]
RC1 is broken! It can't create NuGet packages: https://github.com/dotnet/aspnetcore/issues/35568 and also https://github.com/dotnet/aspnetcore/issues/27740

**Comment by moehoward** [comment]
Yes, that appears to be the snag.
I will give your component a try with RC2 and let you know the outcome.
Thanks!

**Comment by VahidN** [comment]
Try V 1.1
