### ISSUE TITLE
Support a non-numeric code or phrase?

### ISSUE THREAD

**Issue by gabephudson** [VahidN/DNTCaptcha.Blazor#10]
Thank you for sharing this great Captcha library. I love all the customization and the fact that it does not rely on a drawing library to generate an image!

I do have a question. Is there a way to generate or pass in a string to be used as the Captcha text instead of one of the numeric based methods? Typing in a number between 1-20 in many cases does not provide enough protection from guesses/brute force.

**Comment by VahidN** [comment]
>  Typing in a number between 1-20

You can set [max and min](https://github.com/VahidN/DNTCaptcha.Blazor/blob/main/src/DNTCaptcha.Blazor.WasmSample/Client/Pages/Components/Login.razor#L49-L50) to larger numbers.

**Comment by gabephudson** [comment]
Understand you can set these parameters. As a feature suggestion, one would be able to set a display mode as "Text" or "String" and give the captcha a string to use. (with a callback to get a new string on refresh).  Just a thought. Thanks again!

**Comment by VahidN** [comment]
Don't like it? Don't use it.
