### ISSUE TITLE
Security Problem, easy to bypass captcha

### ISSUE THREAD

**Issue by ajahangard** [VahidN/DNTCaptcha.Blazor#11]
Security problem due to client side Captcha generation.
Since the captcha is generated client side and the text is passed to the client side captcha generation logic, the text in the captcha image is revealed client side!

<img width="583" alt="Screenshot 2024-03-27 111511" src="https://github.com/VahidN/DNTCaptcha.Blazor/assets/21051398/7530bf80-0973-4b79-a865-88cebca9fa21">

It is easy to extract captcha from script and bypass it.
I think the captcha generation logic should be on the server side.

**Comment by VahidN** [comment]
Good luck for that. It' not useful for you? don't use it. It's not secure for you job, don't use it. I'm not going to change not even a single line of it.

**Comment by VahidN** [comment]
There are lots of other JavaScript captcha's like this and Yes! This how a client-side technology like blazor-wasm works. It it's not secure enough for your job, don't use it.
