### ISSUE TITLE
Setting value to string.empty does not create a new value

### ISSUE THREAD

**Issue by MatthewJWatkins** [VahidN/DNTCaptcha.Blazor#17]
I have the Value bound a string value, when I set the value to string.Empty, the captcha image is not recreated, and also the value remains string.Empty. So there is now no way to validate against the image as that value is lost.

Looking at the source, setting the value to string.Empty doesn't then call ShowCaptchaAsync, just sets _value .

**Comment by VahidN** [comment]
[This how](https://github.com/VahidN/DNTCaptcha.Blazor/blob/main/src/DNTCaptcha.Blazor.WasmSample/Client/Pages/Components/Login.razor.cs#L20) you should use it and it's tested and [works here](https://vahidn.github.io/DNTCaptcha.Blazor/).
