### ISSUE TITLE
Error with DNTCaptcha on a page

### ISSUE THREAD

**Issue by Fungusware** [VahidN/DNTCaptcha.Blazor#4]
When I use DNTCaptcha on my index page (routed as /) everyting works as expected. However when I use it on a page with a route such as /contact I am getting the error below.

[2022-11-15T08:47:57.354Z] Error: Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: https://localhost:7284/contact_content/DNTCaptcha.Blazor/scripts/dntCaptcha.js
TypeError: Failed to fetch dynamically imported module: https://localhost:7284/contact_content/DNTCaptcha.Blazor/scripts/dntCaptcha.js
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at DNTCaptcha.Blazor.DntInputCaptcha.LoadScriptsAsync() in F:\Prog\1400\DNTCaptcha.Blazor\src\DNTCaptcha.Blazor\Components\DntInputCaptcha.razor.cs:line 323
   at DNTCaptcha.Blazor.DntInputCaptcha.OnAfterRenderAsync(Boolean firstRender) in F:\Prog\1400\DNTCaptcha.Blazor\src\DNTCaptcha.Blazor\Components\DntInputCaptcha.razor.cs:line 305
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by VahidN** [comment]
`contact_content` ? How did this happen? You should get the .js file from the root of the domain, such as:
```
https://localhost:7284/_content/DNTCaptcha.Blazor/scripts/dntCaptcha.js
```
and not concatenation of the different parts, such as your posted URL:
```
https://localhost:7284/contact_content/DNTCaptcha.Blazor/scripts/dntCaptcha.js
```
[Because of this line](https://github.com/VahidN/DNTCaptcha.Blazor/blob/main/src/DNTCaptcha.Blazor/Components/DntInputCaptcha.razor.cs#L16).

Here is a sample to show it in a subdomain with a routed page:
https://vahidn.github.io/DNTCaptcha.Blazor/routed-login-page
[Also you can run it locally if you want](https://github.com/VahidN/DNTCaptcha.Blazor/blob/main/src/DNTCaptcha.Blazor.WasmSample/Client/Pages/RoutedPage.razor#L1).

**Comment by Fungusware** [comment]
So I have a Contact Form component that I use in both places. On the Index page it works, but not on the Contacts page.

I'm not constructing that URL __content/DNTCaptcha.Blazor/scripts/dntCaptcha.js_ That is what is being generated.

**Comment by VahidN** [comment]
I can't reproduce your issue.
- [I moved](https://github.com/VahidN/DNTCaptcha.Blazor/blob/main/src/DNTCaptcha.Blazor.WasmSample/Client/Pages/Components/Login.razor) the whole login fields to a new component.
- [I added](https://github.com/VahidN/DNTCaptcha.Blazor/blob/main/src/DNTCaptcha.Blazor.WasmSample/Client/Pages/RoutedPage.razor) a new routed page sample.
And it's still working without any issues (locally and [also here](https://vahidn.github.io/DNTCaptcha.Blazor/routed-login-page) in a subdomain)

**Comment by Fungusware** [comment]
Does it do the same in Blazor Server ?

**Comment by VahidN** [comment]
[Yes. I updated that sample too.](https://github.com/VahidN/DNTCaptcha.Blazor/tree/main/src/DNTCaptcha.Blazor.ServerSample/Pages) You can download it and test it locally.

**Comment by Fungusware** [comment]
Can I invite you to my Repo, see if you can see whats going on. I've tried it all.

Your sample worked ok,

**Comment by VahidN** [comment]
Don't remove the [base href](https://github.com/VahidN/DNTCaptcha.Blazor/blob/main/src/DNTCaptcha.Blazor.ServerSample/Pages/_Host.cshtml#L14) from the `_Host.cshtml` file:
```xml
<base href="~/"/>
```
The <base href='' > is a [client side technology](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) that specifies the base URL for all relative URLs in current document.

**Comment by Fungusware** [comment]
You Sir, are amazing !
