### ISSUE TITLE
Captchas update each other constantly

### ISSUE THREAD

**Issue by HerzogVolpe** [VahidN/DNTCaptcha.Blazor#5]
# Summary of the issue
on the example-page, when you spam the captcha refresh-button, the captcha starts to update the other captchas and the other captchas update the first one, looks like they are triggering each other.

## Environment
linked example-page on github
```
DNTCaptcha.Blazor version: linked example-page on github
.NET Core SDK version: linked example-page on github
```

## Example code/Steps to reproduce:
spamm the refresh captcha-button very fast
```C#
paste your core code 
```
linked example-page on github
## Output:
permanently updating captcha
```
this is nothing game breaking, at least not for me, just wanted to let you know :-)

**Comment by VahidN** [comment]
Probably Blazor calls the state has changed and re-renders the whole page. Don't worry about it.
